# Generated by Django 6.0.3 on 2026-03-21 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('browser', models.CharField(blank=True, max_length=100, null=True)),
                ('device', models.CharField(blank=True, max_length=100, null=True)),
                ('path', models.CharField(max_length=500)),
                ('is_unique', models.BooleanField(default=False)),
                ('visit_date', models.DateField(auto_now_add=True)),
                ('visit_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
